spring.application.name=SpringJPAHibernate
spring.datasource.url=jdbc:mysql://localhost:3306/SpringJPAHibernate?createTableIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Itachiuchiha52@
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kritiraj.exams2021@gmail.com
spring.mail.password=keir uwxi eagu lsuo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

LOG_PATH=logs
LOG_FILE=customer-service
FILE_PATTERN=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always



