spring.application.name=SpringJPAHibernate
spring.datasource.url=jdbc:mysql://localhost:3306/SpringJPAHibernate?createTableIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Itachiuchiha52@
spring.jpa.hibernate.ddl-auto=update

